### ISSUE TITLE
"Path" argument must be of type string error when used in node-steam-user

### ISSUE THREAD

**Issue by mstan** [DoctorMcKay/node-stdlib#3]
Filing an issue here for an error I'm seeing while use node-steam-user, which seems to be getting called in this library instead.

Background context: I'm developing a multi-purpose bot that has multiple clients, one of which is a steam bot. The stack trace is originating a "new" call:

```
const SteamUser = require('steam-user');
...
const client = new SteamUser(); // stack trace fires here
```

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at Object.OS.appDataDirectory (/var/www/egnisv3/node_modules/@doctormckay/stdlib/components/os.js:31:17)
    at new SteamUser (/var/www/egnisv3/node_modules/steam-user/index.js:78:44)
    ... {
  code: 'ERR_INVALID_ARG_TYPE'
}

As far as I can tell, components/os.js:31 is using `process.env.HOME` and isn't doing any sort of safety check if it's null or undefined, which `path` doesn't seem to like. 

This only occurs when I deploy my bot to my Ubuntu VPS. It doesn't appear to occur on Windows.

**Comment by DoctorMcKay** [comment]
Thanks for the report, this is fixed now.
