### ISSUE TITLE
Can  307 redirect be supported for HttpClient ?

### ISSUE THREAD

**Issue by tre0521** [DoctorMcKay/node-stdlib#6]
if (options.followRedirects && REDIRECT_STATUS_CODES.includes(res.statusCode) && res.headers.location) {
						let newRequest = clone(options);
						if ([301, 302, 303].includes(res.statusCode)) {
							// Change the method to GET
							newRequest.method = 'GET';
							newRequest.url = res.headers.location;
							delete newRequest.body;
							delete newRequest.headers['content-type'];
							delete newRequest.headers['content-length'];
							this.request(newRequest).then(resolve).catch(reject);
							return;
						}
					}

**Comment by DoctorMcKay** [comment]
307 is [already supported](https://github.com/DoctorMcKay/node-stdlib/blob/master/src/lib/http/client/HttpClient.ts#L24). The check you quoted is to prevent 307 redirects from changing the request method to GET, which should not happen for 307 and 308 redirects:

> The difference between 307 and 302 is that 307 guarantees that the client **will not change** the request method and body when the redirected request is made.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307
